using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bullet : MonoBehaviour
{
    Rigidbody2D rb;
    public float bulletSpeed; 
    public float endTime;
    void Start()
    {
       rb = GetComponent<Rigidbody2D>();
       rb.velocity = transform.right* bulletSpeed;
       Destroy(gameObject,endTime);
    }

    private void OnTriggerEnter2D(Collider2D collision) {
        if(collision.CompareTag("Enemy")){

            collision.GetComponent<enemy>().damage(1);
            Destroy(gameObject);
           // Debug.Log("Canı yandı!");
        }
    }
     
    
}
